name: Release
description: Release the application
inputs:
  GH_TOKEN:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20.19.0
        registry-url: 'https://npm.pkg.github.com'
        scope: '@rohithart' 
    - name: Install Dependencies
      run: yarn install
      shell: bash
    - name: Build
      run: yarn build
      shell: bash
    - name: Prepare dist for publishing
      run: |
        cp package.json README.md CHANGELOG.md ./dist/ 2>/dev/null || :
        cd dist && npm pkg delete scripts devDependencies
      shell: bash

    - name: Release application
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
        NODE_AUTH_TOKEN: ${{ inputs.GH_TOKEN }}
