name: Sanity check
description: Sanity check the application
inputs:
  GH_TOKEN:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: ./.github/actions/set-up

    - name: Run Lint
      run: yarn lint
      shell: bash
