name: Sanity check
description: Sanity check the application
inputs:
  GH_TOKEN:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Read .nvmrc
      run: |
        NODE_VERSION=$(cat .nvmrc)
        echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_ENV
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Dependencies
      run: yarn install
      shell: bash

    - name: Run Lint
      run: yarn lint
      shell: bash
